# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
 
pool:
  name: pool1
 
steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'

- script: |
    echo Simulating deployment...
    if not exist deployed mkdir deployed
    copy target\*.jar deployed\
    dir deployed
    echo Deployment successful!
  displayName: 'Simulate Deployment'
 
- script: |
    echo "Contents of deployed folder:"
    dir deployed
  displayName: 'Verify Deployment Output'
